services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    volumes:
      - ./server/config.ini:/config.ini
    networks:
      - generator_network
  client1:
    container_name: client1
    image: client:latest
    environment:
      - CLI_ID=1
      - CLI_LOG_LEVEL=DEBUG
      - NOMBRE=Santiago Lionel
      - APELLIDO=Lorca
      - DOCUMENTO=30904465
      - NACIMIENTO=1999-03-17
      - NUMERO=7574
    volumes:
      - ./client/config.yaml:/config.yaml
    networks:
      - generator_network
    depends_on:
      - server

networks:
  generator_network:
    name: generator_network
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
